[features]
seeds = false
[programs.localnet]
hm_swap = "C96yQo42vnEbpSxb2AzX4ZYzVvnocaHtw8nSBxLK4hGG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/bmstart/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
